server:
  port: 8080

arena:
  turn:
    duration-ms: 1000
    tick-check-ms: 100
  kafka:
    topic: arena.match-events.v1
    lifecycle-topic: arena.match-lifecycle.v1
    action-topic-pattern: .*\.match-actions\.v1

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: arena-engine
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.json.reader: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
      properties:
        schema.registry.url: http://localhost:8081
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        auto.register.schemas: true
        use.latest.version: false
        normalize.schemas: true
        enable.idempotence: true
        acks: all
        max.in.flight.requests.per.connection: 1
    admin:
      properties:
        bootstrap.servers: localhost:9092
